/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dron/drone_for_agriculturelow_poly.glb -o src/components/DroneModel.tsx -t 
Author: Bharat Nagar (https://sketchfab.com/bharat1752nagar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drone-for-agriculturelow-poly-b6220a9a99d349d5aa64c8e7edef3758
Title: Drone For agriculture(Low Poly)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube1_Drone_0: THREE.Mesh
    pCylinder23_Drone_0: THREE.Mesh
    polySurface24_Drone_0: THREE.Mesh
    polySurface25_Drone_0: THREE.Mesh
    pCylinder20_Drone_0: THREE.Mesh
    polySurface5_Drone_0: THREE.Mesh
    polySurface11_Drone_0: THREE.Mesh
    pCylinder19_Drone_0: THREE.Mesh
    pCylinder13_Drone_0: THREE.Mesh
    polySurface6_Drone_0: THREE.Mesh
    pCylinder14_Drone_0: THREE.Mesh
    polySurface7_Drone_0: THREE.Mesh
    pCylinder15_Drone_0: THREE.Mesh
    polySurface8_Drone_0: THREE.Mesh
    pCylinder16_Drone_0: THREE.Mesh
    polySurface9_Drone_0: THREE.Mesh
    pasted__Body60_Drone_0: THREE.Mesh
    pCylinder17_Drone_0: THREE.Mesh
    polySurface18_Drone_0: THREE.Mesh
    polySurface19_Drone_0: THREE.Mesh
    polySurface20_Drone_0: THREE.Mesh
    polySurface21_Drone_0: THREE.Mesh
    polySurface22_Drone_0: THREE.Mesh
    polySurface23_Drone_0: THREE.Mesh
    polySurface4_Drone_0: THREE.Mesh
    polySurface10_Drone_0: THREE.Mesh
    pCylinder6_Drone_0: THREE.Mesh
    pasted__Body105_Drone_0: THREE.Mesh
    pasted__Body106_Drone_0: THREE.Mesh
    pasted__Body107_Drone_0: THREE.Mesh
    pasted__Body108_Drone_0: THREE.Mesh
    pasted__Body109_Drone_0: THREE.Mesh
    polySurface13_Drone_0: THREE.Mesh
    polySurface14_Drone_0: THREE.Mesh
    polySurface15_Drone_0: THREE.Mesh
    polySurface16_Drone_0: THREE.Mesh
    pCylinder26_Drone_0: THREE.Mesh
    pCylinder7_Drone_0: THREE.Mesh
    pCylinder31_Drone_0: THREE.Mesh
    pCylinder32_Drone_0: THREE.Mesh
    pCylinder33_Drone_0: THREE.Mesh
    pCube6_Drone_0: THREE.Mesh
    pCylinder34_Drone_0: THREE.Mesh
    pCylinder35_Drone_0: THREE.Mesh
    pCylinder36_Drone_0: THREE.Mesh
    pCylinder37_Drone_0: THREE.Mesh
  }
  materials: {
    Drone: THREE.MeshStandardMaterial
  }
}

export function Model() {
  const { nodes, materials } = useGLTF('/drone_for_agriculturelow_poly.glb') as unknown as GLTFResult
  return (
    <group dispose={null}>
      <group scale={0.01}>
        <group position={[0, -0.365, 0.031]}>
          <mesh geometry={nodes.polySurface24_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface25_Drone_0.geometry} material={materials.Drone} />
        </group>
        <group rotation={[0, Math.PI / 6, 0]}>
          <mesh geometry={nodes.pCylinder20_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface5_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface11_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder19_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder13_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface6_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder14_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface7_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder15_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface8_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder16_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface9_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body60_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder17_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface18_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface19_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface20_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface21_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface22_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface23_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface4_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.polySurface10_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pCylinder6_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body105_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body106_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body107_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body108_Drone_0.geometry} material={materials.Drone} />
          <mesh geometry={nodes.pasted__Body109_Drone_0.geometry} material={materials.Drone} />
        </group>
        <mesh geometry={nodes.pCube1_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder23_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.polySurface13_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.polySurface14_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.polySurface15_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.polySurface16_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder26_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder7_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder31_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder32_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder33_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCube6_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder34_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder35_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder36_Drone_0.geometry} material={materials.Drone} />
        <mesh geometry={nodes.pCylinder37_Drone_0.geometry} material={materials.Drone} />
      </group>
    </group>
  )
}

useGLTF.preload('/drone_for_agriculturelow_poly.glb')
