/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pineapple/lamborghini_tractor_r6_125_dcr__www.vecarz.com.glb -o src/components/TractorModel.tsx -t 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-tractor-r6-125-dcr-wwwvecarzcom-56d7c8e7e2cb4d15a3d80cc42c697c53
Title: Lamborghini Tractor R6 125 DCR | www.vecarz.com
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import {useEffect} from 'react'

type GLTFResult = GLTF & {
  nodes: {
    lamborghini_BODY_Cuz_0: THREE.Mesh
    WINDOW_Lob_0: THREE.Mesh
    lamborghini_SUB2_Shin_0: THREE.Mesh
    lamborghini_COCKPIT_Salon_0: THREE.Mesh
    lamborghini_Nacl_0: THREE.Mesh
    WHEEL_LF_Shin_0: THREE.Mesh
    WHEEL_LR_Shin_0: THREE.Mesh
    WHEEL_RF_Shin_0: THREE.Mesh
    WHEEL_RR_Shin_0: THREE.Mesh
    SUSP_LF_Cuz_0: THREE.Mesh
    SUSP_RF_Cuz_0: THREE.Mesh
    STEER_HR_Salon_0: THREE.Mesh
    LIGHT_Cuz_0: THREE.Mesh
    MIRROR_R_MIRROR_0: THREE.Mesh
    MIRROR_L_MIRROR_0: THREE.Mesh
    BRAKE_Cuz_0: THREE.Mesh
    B_Cuz_0: THREE.Mesh
    car_wiper_R_Cuz_0: THREE.Mesh
    car_wiper_F_Cuz_0: THREE.Mesh
    LAMP_Cuz_0: THREE.Mesh
    WINDOW_IN_in_win_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshPhysicalMaterial
    material_1: THREE.MeshStandardMaterial
    Shin: THREE.MeshPhysicalMaterial
    Salon: THREE.MeshStandardMaterial
    Nacl: THREE.MeshStandardMaterial
    MIRROR: THREE.MeshStandardMaterial
    in_win: THREE.MeshStandardMaterial
  }
}

export function Model({ onLoaded, ...props }: any) {
  const gltf = useGLTF('/models/pineapple/lamborghini_tractor_r6_125_dcr__www.vecarz.com.glb');
  const { nodes, materials } = gltf as unknown as GLTFResult;

  useEffect(() => {
    if (gltf && onLoaded) {
      onLoaded();
    }
  }, [gltf]);

  return (
    <group {...props} dispose={null}>
      <group scale={5}>
        <mesh geometry={nodes.WHEEL_LF_Shin_0.geometry} material={materials.Shin} position={[0.933, 0.711, 1.566]} />
        <mesh geometry={nodes.WHEEL_LR_Shin_0.geometry} material={materials.Shin} position={[0.916, 0.987, -1.16]} />
        <mesh geometry={nodes.WHEEL_RF_Shin_0.geometry} material={materials.Shin} position={[-0.933, 0.711, 1.566]} />
        <mesh geometry={nodes.WHEEL_RR_Shin_0.geometry} material={materials.Shin} position={[-0.916, 0.987, -1.16]} />
        <mesh geometry={nodes.SUSP_LF_Cuz_0.geometry} material={materials.material} position={[0.933, 0.711, 1.566]} />
        <mesh geometry={nodes.SUSP_RF_Cuz_0.geometry} material={materials.material} position={[-0.933, 0.711, 1.566]} />
        <mesh geometry={nodes.STEER_HR_Salon_0.geometry} material={materials.Salon} position={[0.001, 2.288, -0.198]} rotation={[0.856, 0, 0]} />
        <mesh geometry={nodes.lamborghini_BODY_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.WINDOW_Lob_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.lamborghini_SUB2_Shin_0.geometry} material={materials.Shin} />
        <mesh geometry={nodes.lamborghini_COCKPIT_Salon_0.geometry} material={materials.Salon} />
        <mesh geometry={nodes.lamborghini_Nacl_0.geometry} material={materials.Nacl} />
        <mesh geometry={nodes.LIGHT_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.MIRROR_R_MIRROR_0.geometry} material={materials.MIRROR} />
        <mesh geometry={nodes.MIRROR_L_MIRROR_0.geometry} material={materials.MIRROR} />
        <mesh geometry={nodes.BRAKE_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.B_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.car_wiper_R_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.car_wiper_F_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.LAMP_Cuz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.WINDOW_IN_in_win_0.geometry} material={materials.in_win} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/pineapple/lamborghini_tractor_r6_125_dcr__www.vecarz.com.glb');